export const menuItems = [
  {
    title: "Ordenes",
    description: "Lista de ordenes disponibles.",
    icon: "ORD",
    color: "#7C3AED",
    route: "/(tabs)/orders",
  },
  {
    title: "Revision manual",
    description: "Revision manual de ordenes.",
    icon: "REV",
    color: "#7C3AED",
    route: "/(tabs)/manual-review",
  },
  {
    title: "Notificaciones",
    description: "Conexion y confirmaciones del sistema.",
    icon: "SIG",
    color: "#4F46E5",
    route: "/payment-status",
  },
  {
    title: "Registrar SINPE",
    description: "Procesar un mensaje de pago SINPE Movil.",
    icon: "SMS",
    color: "#0F766E",
    route: "/sinpe-message",
  },
  {
    title: "Historial",
    description: "Ordenes y pagos procesados.",
    icon: "HIS",
    color: "#6366F1",
    route: "/transaction-history",
  },
  {
    title: "Fraudes",
    description: "Intentos de pago sospechosos.",
    icon: "FRD",
    color: "#E85D75",
    route: "/fraud-attempts",
  },
  {
    title: "Monitoreo",
    description: "Estado de conexion del telefono POS.",
    icon: "POS",
    color: "#28A745",
    route: "/device-status",
  },
] as const;
